FROM node:20

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 make g++ && \
    npm install -g @napi-rs/cli

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]